// Runtime skill definitions for dsh-hdc-bridge.
// The `deveco-cli` skill is an adaptation (translated summary, not a verbatim
// copy) of the official SKILL.md from gitcode.com/openharmony-sig/deveco-cli,
// licensed MIT — Copyright (c) 2026 Huawei Device Co., Ltd. The notice line is
// reproduced inside the skill content and checked by scripts/license-check.mjs.
//
// DSH runtime skills must carry BOTH `content` (rendered instructions body)
// and `source` (the raw source string) — the loader rejects one without the
// other with "loaded skill ... source must be a string".
const skill = (def) => ({ ...def, source: def.source ?? def.content })

export const SKILLS = [
  skill({
    name: 'hdc-bridge',
    description: '鸿蒙真机/模拟器设备调试闭环（hdc-bridge）：查看界面、定位控件、点击/输入/滑动、截图验证、装包/卸载、崩溃排查、hilog 日志、环境体检（hms_setup）——观察-定位-操作-验证循环。',
    whenToUse: '在已装载 hdc_* 工具的会话里操作 HarmonyOS 真机/模拟器：查看界面、定位控件、点击/输入、截图验证、装包/卸载、崩溃与 hilog 日志排查、环境体检（hms_setup）。',
    content: '# dsh-hdc-bridge 设备调试闭环\n\n本技能只讲设备调试工具的用法；ArkTS/API 知识请用 `harmonyos-knowledge` 技能（官方优先、按版本）。\n\n## 闭环流程\n1. hdc_list_targets 确认设备（默认取第一个 Connected 目标，可用 target 覆盖）\n2. hdc_ui_dump 查看当前界面文本（文本版截图）\n3. hdc_ui_find 按文本定位控件（返回 bounds 与中心坐标）\n4. hdc_ui tap / input / swipe / key 操作（每步后用最新 dump 坐标）\n5. hdc_ui_dump 验证状态变化\n\n- 视觉模型：hdc_screenshot → read_image\n- 排查：hdc_crash（结构化崩溃摘要）/ hdc_hilog（hilog 尾部）/ hdc_diag（插件状态）；按关键词批量收集或清日志缓冲 → hdc_log（deveco-compile 技能）\n- 生命周期：hdc_install（装包）/ hdc_app（query/start/stop/clear-data/uninstall）\n- 环境体检：hms_setup（hdc/Studio/SDK/devecocli/设备 五项）\n\n## 实测经验（本插件团队验证）\n- 混合字符串输入（数字→字母→数字）：IME 模式切换会稳定吞掉紧跟字母后的字符 → 分段输入 + dump 校验 + 缺失字符补发\n- 软键盘弹出会改变页面布局：每次点击前使用最新 dump 的坐标；按钮被键盘遮挡时先 hdc_ui key Back 收起键盘\n- snapshot_display 仅接受 .jpeg（API 10+）\n- hdc_ui_dump 空树 ≠ 页面无内容：锁屏/启动中/窗口未 attach 都会 dump 到 0 节点——空树时看返回的 diagnosis 与 aa dump -a 前台列表，必要时截图确认\n- 装包报 9568332 = 签名 profile 未绑定设备 UDID，需在 AGC 添加设备后重新签名\n- hdc 客户端对远端失败可能仍返回退出码 0：以工具返回的 ok/error 字段为准\n',
  }),
  skill({
    name: 'deveco-cli',
    description: '华为官方 DevEco CLI（devecocli）通道：构建/运行/签名/登录、官方 lint、本地官方文档、跨版本兼容扫描、模拟器管理——对应 hms_build、hms_lint、hms_docs、hms_api_change 的底层命令与约束。',
    whenToUse: '需要用官方工具链构建/签名/运行、跑官方 lint、查官方本地文档、扫描跨版本破坏性 API 变更、管理模拟器或账号登录时；或用户提到 devecocli/DevEco CLI。',
    content: [
      '# DevEco CLI（devecocli）技能',
      '',
      '> 本技能改写自华为官方仓库 SKILL.md（翻译摘要，非逐字复制）。',
      '> Copyright (c) 2026 Huawei Device Co., Ltd. — MIT License.',
      '> 官方原文：https://gitcode.com/openharmony-sig/deveco-cli/blob/develop/SKILL.md',
      '',
      '## 入口（本插件工具，优先用它们，参数已校验）',
      '- hms_build：status / build / run / sign / clean（CLI 缺失时自动回退本机 hvigorw）',
      '- hms_lint：rules（本机 57+ 官方规则索引）/ read-rule / check（devecocli check lint）',
      '- hms_docs：search / read / catalog（devecocli docs，官方本地文档库）',
      '- hms_api_change：versions / diff（devecocli check compat，官方跨版本破坏性变更扫描）',
      '- hms_emulator：模拟器生命周期 list / start / stop / status（devecocli emulator，设备名是位置参数；沙箱内受 mojo 通道限制需 [Outside sandbox]）',
      '',
      '## 与编译闭环的分工',
      '- 纯编译/打包/推包启动（无签名问题）→ 优先 `deveco-compile` 技能的 build_project / start_app（参数已校验、输出友好）',
      '- 本技能侧重 CLI 全通道：签名/登录（auth login、signature generate）、check compat、docs、emulator、lint 检查、hvigor 兜底',
      '',
      '## 直接命令速查（devecocli 已随插件作为 optionalDependency 安装）',
      '- `build`：编译打包。`--modules <m1> <m2>@<target>` 指定模块；`--product <name>` 打整包；`build clean` 清理。',
      '- `run`：构建+安装+启动。`--module`、`--device <name|serial>`（多设备必填）、`--uninstall`（先卸载，解决签名 key 变更）、`--skip-build`、`--apply <file>` 增量快速部署（Studio ≥6.1.1）。',
      '- `check lint [path]`：官方 ArkTS lint。`--fix`、`--format json`（需 Studio ≥6.0）、`--limit <n>`。',
      '- `check compat`：扫描两个 SDK 版本间的破坏性 API 变更。`versions` 列可用版本；`--source-version X --target-version Y --format json --output-path <dir>`；必须 target > source。',
      '- `signature generate`：自动生成签名材料并写入 build-profile.json5。前置：`auth login` + 项目目录 + 已连接设备。',
      '- `auth login/status/logout`：华为开发者账号 OAuth（浏览器人工步骤）。',
      '- `docs search <kw>` / `docs read <id>` / `docs catalog`：官方本地文档检索。',
      '- `emulator list`（无参，列全部设备）/ `emulator start <name>` / `emulator stop <name>`：设备名是位置参数（如 "MatePad Pro 13"，以 `emulator list` 显示为准），一次可接多个名；实测无 `--name` 旗标',
      '- `ui layout/screenshot/click/text`、`log --crash --bundle-name X`、`create --app-name X --api-level N`、`skills list/add`。',
      '',
      '## 硬性约束',
      '- 仅 macOS/Windows；Node ≥18；构建/签名/lint 需本机 DevEco Studio ≥6.0（lint 默认），`--format json` 需 ≥6.1.0，`--apply` 需 ≥6.1.1。',
      '- 官方标注 [Outside sandbox]：build / run / signature generate / update / check compat —— 在受限沙箱中运行时提示用户放宽策略或人工执行。',
      '- 签名前置 `auth login` 是浏览器 OAuth，Agent 无法代办；未登录时给用户命令，不重试。',
      '',
      '## 错误速查',
      '- `Not logged in` → devecocli auth login',
      '- `error:install sign info inconsistent` → devecocli run --uninstall 或 signature generate --force',
      '- `Provision number exceeds limit` → AGC 控制台删旧测试 profile',
      '- `Product / Build mode not found` → 检查 build-profile.json5',
      '- `Multiple entry modules` → build 加 --modules，run 加 --module',
    ].join('\n'),
  }),
  skill({
    name: 'harmonyos-knowledge',
    description: '鸿蒙知识层纪律：官方优先、按 API 版本分类、许可合规。回答 ArkTS/ArkUI/API 用法、某 API 的版本可用性（@since/@deprecated）或官方文档之前先走 hms_knowledge / hms_api / hms_docs / hms_api_change / hms_lint。',
    whenToUse: '回答任何 ArkTS / ArkUI / API 能力、版本兼容性、废弃 API、lint 规范问题之前；或需要判断某 API 在目标版本是否可用时。',
    content: [
      '# 鸿蒙知识层使用纪律（官方优先、版本化、许可合规）',
      '',
      '## 数据源层级（严格按序，上层优先）',
      '**Tier 0 官方一手（本机运行时读取，随用户工具链版本，零再分发）**',
      '- hms_api：本机 SDK .d.ts，每条 API 带 @since/@deprecated/@syscap，精确到 API 版本 —— 回答"某 API 何时有/何时废弃"的首选',
      '- hms_docs：devecocli 官方本地文档库（开发指南/API 参考）',
      '- hms_api_change：官方跨版本破坏性变更扫描（check compat）',
      '- hms_lint rules：本机 DevEco 内置官方 lint 规则（Apache-2.0，本地读取）',
      '**Tier 1 随包内置（离线可用，无需 Studio/SDK/网络）**',
      '- hms_knowledge：OpenHarmony 官方文档逐字节选（CC-BY-4.0 已署名）—— 20 个高频 API 模块（promptAction/router/notification/vibrator/http/ws/preferences/util/uiAbility/权限/context…）+ 应用模型与 ArkTS 状态管理指南。catalog 列题 → read 先看目录再按小节读 → search 按关键词找题/小节',
      '- deveco-cli 技能（官方 SKILL.md 改写，MIT 已声明）',
      '**Tier 2 用户自装（仅指路，绝不随包）**：harmony-next.skills 等社区包（无 LICENSE，不可再分发）；官方 web 文档 developer.huawei.com（在线检索时优先官方站）',
      '',
      '## 查询速查',
      '- 概念/用法/示例（人读文档）：先 hms_knowledge（离线随包，秒回）；全量官方库走 hms_docs（需 devecocli）',
      '- 签名/版本/废弃判定（机读精确）：hms_api 的 @since/@deprecated/@syscap',
      '- 文档正文里的"起始版本/API version"标注同样可信，回答时同步标注',
      '',
      '## 官方测试框架指路（canonical 在 ohpm/Gitee，不在 GitHub）',
      '- hypium（@ohos/hypium，Apache-2.0）：官方单元测试框架，describe/it/expect 风格，支持 HAP/HAR 测试；仓库 gitee.com/openharmony/testfwk_arkxtest，ohpm 安装',
      '- hamock（@ohos/hamock，Apache-2.0）：官方 mock 框架，与 hypium 配对做依赖替换；同一仓库的 hamock/ 子目录',
      '- 这两个项目没有 GitHub canonical——找源码与示例以 Gitee/ohpm 为准；仅指路，不复制内容',
      '',
      '## 版本纪律（鸿蒙知识随版本变化，不止新增）',
      '1. 回答问题前先确定目标 API 版本：hms_setup 一次取齐三处来源 —— 项目 build-profile.json5 compatibleSdkVersion → 设备 `param get const.ohos.apiversion` → 本机 SDK apiVersion',
      '2. 三处不一致时显式提示用户（例如 SDK=23 而真机=24），并建议用 hms_api_change diff 查差异',
      '3. API 标注 @since N 表示 N 起才存在；@deprecated since M 表示 M 起不推荐，找替代 API',
      '4. 旧版知识回答新版问题 = 高危错误：宁可先 hms_api 查询再回答',
      '5. 引用知识时标注来源层级与版本（如 "hms_api@SDK23：since 15，目标 23 可用"）',
      '',
      '## 许可纪律',
      '- 本机读取（SDK .d.ts / codelinter 规则）= 合法，但不得把这些内容复制进生成物再分发',
      '- 无 LICENSE 资源只可引用链接，不可复制内容',
      '- 引用官方内容时保留版权与来源',
    ].join('\n'),
  }),
  skill({
    name: 'deveco-compile',
    description: '鸿蒙编译构建闭环：switch_cwd → arkts_check → build_project → start_app → hdc_log（工程根切换 / ArkTS 静态检查 / 打包构建 / 推包启动 / 设备日志）。设备级调试（截图/UI 操作/装包/崩溃）用 hdc-bridge 技能。',
    whenToUse: '需要编译/打包构建鸿蒙工程、编译前快速静态检查 .ets、推包启动应用、按关键词收集/清理设备日志时；或用户提到 build_project / arkts_check / switch_cwd / start_app / hdc_log。',
    content: [
      '# 鸿蒙编译辅助闭环（deveco-compile）',
      '',
      '## 闭环流程',
      '1. `switch_cwd`：把会话的鸿蒙工程根指到目标项目（后续工具默认用该目录；跳过则用工作区根）',
      '2. `arkts_check`：写/改完 .ets 后先静态检查（比整包构建快，返回 file:line:col + 规则名）',
      '3. `build_project`：编译打包（默认 --product default --build-mode debug；clean 仅用户明确要求时用 true）',
      '4. `start_app`：devecocli run --skip-build 推到真机/模拟器；不填 hvd 会列出设备供选择，选未运行的模拟器会自动启动',
      '5. `hdc_log`：collect（按 log_prefix 关键词过滤）/ clear（hilog -r 清缓冲）/ list_devices（列设备）',
      '',
      '## 与既有工具的分工',
      '- 设备上"看-点-输-验证"闭环（截图/UI dump/装包/崩溃/生命周期）→ `hdc-bridge` 技能的 hdc_* 工具',
      '- 签名/登录/授权通道 → `deveco-cli` 技能的 hms_build（sign、auth login 等）',
      '- 模拟器生命周期（list/start/stop/status）→ `hms_emulator`（devecocli emulator，设备名是位置参数）',
      '- start_app 在 devecocli 设备发现被沙箱 mojo 阻断时会自动回退 hdc：装最新 .hap + aa start',
      '- 官方 lint 规范（codelinter 57+ 规则）→ hms_lint；本技能专注编译期检查（ets-loader）',
      '- ArkTS/API 版本与用法问题 → `harmonyos-knowledge` 技能（hms_api / hms_knowledge 等）',
      '',
      '## 硬性约束',
      '- build/start_app 走 devecocli（optionalDependency 随插件安装）；devecocli 缺失时工具返回安装指引',
      '- arkts_check 需要本机 DevEco Studio（SDK ets-loader，DevEco ≥ 6.0 实测）；未安装时返回指引，改走 build_project 完整构建',
      '- 官方标注 [Outside sandbox]：build / run 会派生 hvigor（用户级缓存在工作区外），受限沙箱里可能 EPERM——按提示升级会话策略或人工执行',
      '- start_app 不构建：先 build_project 再 start_app（或需要签名时用 hms_build 的 run 通道）',
      '',
      '## 错误速查',
      '- `HarmonyOS project not found at ...` → 目录不是工程根：先 switch_cwd 指向含 build-profile.json5 的根',
      '- `BUILD FAILED (exitCode=...)` → 看尾部 50 行定位报错文件；hvigor 有时带警告仍非零退出，以输出标记为准',
      '- `run` 找不到设备 → start_app 不带 hvd 列出可选设备；停止的模拟器会自动启动',
      '- `Not logged in`（签名场景）→ devecocli auth login（浏览器 OAuth，Agent 无法代办）',
      '- `error:install sign info inconsistent` → hms_build 的 sign 通道或 `devecocli run --uninstall`',
    ].join('\n'),
  }),
]
